### ISSUE TITLE
tanzu CLI should support different editions without re-installing binaries

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#1219]
## Feature Request

There will be people using both Tanzu Community Edition and the commercial versions of Tanzu Kubernetes Grid. We need to make sure they are able to use and install the tanzu CLI without interfering with each other.

## Describe alternatives you've considered

Current situation is it is recommended not to try to manage both on the same machine. But early feedback is this is going to be a major pain point for many users.

**Comment by joshrosso** [comment]
Due to the need for:

* https://github.com/vmware-tanzu/community-edition/issues/3275

This will not make it in for v0.11.0. We'll revisit this in v0.12.0. Note that this is not possible until we jump to to framework v0.17.0, as that is where the work to dynamically change compatibility files came in.

**Comment by joshrosso** [comment]
Let's continue to track this work in:

* https://github.com/vmware-tanzu/community-edition/issues/2716

Current status is that we are going to re-assess if this is viable in the `v0.13.0` timeframe.
