### ISSUE TITLE
[Docs] Docker Standalone Cluster Instructions on CLI vs UI

### ISSUE THREAD

**Issue by pnbrown** [vmware-tanzu/community-edition#1429]
## Bug Report
Other options on the cluster create for standalone clusters instruct users to complete via the UI. Docker does not.

## Expected Behavior

Uniformity of options on the cluster create that addresses all options for install via the UI.

**Comment by stmcginnis** [comment]
This issue was related to our deprecated and removed standalone cluster feature. Things have been greatly simplified now with our move to unmanaged clusters. I don't think this requires any action now, so I am going to close it out. Please feel free to reopen or file a new issue if there is still something missing.
