### ISSUE TITLE
Can we hide "CheckControllerStatus is disabled for this session, not going to retry" when checking Avi connectivity?

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/community-edition#1634]
## Feature Request

When we do the Avi connectivity check in the UI, the following messages are thrown in the CLI:

```
% tanzu management-cluster create --ui

Validating the pre-requisites...
Serving kickstart UI at http://127.0.0.1:8080
E0909 09:04:31.721860    2053 avisession.go:714] CheckControllerStatus is disabled for this session, not going to retry.
E0909 09:04:31.751117    2053 avisession.go:714] CheckControllerStatus is disabled for this session, not going to retry.
E0909 09:04:31.840045    2053 avisession.go:714] CheckControllerStatus is disabled for this session, not going to retry.
```

Could we hide these messages from the user to provide a better UX?

## Describe alternatives you've considered

N/A

## Environment Details

- Build version (tanzu version):

    version: v1.4.0-pre-alpha-2
    buildDate: 2021-08-19
    sha: 75cfa0e

- Operating System (client):

    macOS (Big Sur) v11.5.2.
    vSphere 7.0U2c
    NSX ALB (Avi Vantage) v2.0.1.5.

**Comment by mritunjaysharma394** [comment]
I think this behaviour is due to the below line of code? 
https://github.com/vmware-tanzu/community-edition/blob/438ba11825108fc5281d10d2c198c9085c6e641b/cli/cmd/plugin/standalone-cluster/create.go#L119

Can we think of removing it if it is not required or there's a better alternative to fix it? Thanks a lot!
