### ISSUE TITLE
TCE acronym still appears in the UI

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#1683]
AFAIU from marketing folks - TCE acronym is not allowed and it should be full name in all places:
Tanzu Community Edition

**Comment by stmcginnis** [comment]
Actually, it was easier than I thought. :)

I see two places where TCE is somewhere visible. The first is in the UI landing page:

https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/tkg/web/src/app/shared/constants/branding.constants.ts#L35

In this case, it is mentioned as an acronym after calling out the full "Tanzu Community Edition" name, so I believe this is acceptable.

The other place is some debugging output when starting the web server to serve the kickstart UI:

https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/tkg/web/node-server/src/www.js#L98

That case only uses the acronym. But I think since this is basically just debug output that isn't in the full UI, it's probably acceptable.

I'm going to close this since I think the original issue has probably been addressed by a different PR. If that's not the case and you think anything above isn't accurate, please feel free to reopen.
