### ISSUE TITLE
Help picking an instance type: Ensure we at minimum filter instance types that will not work

### ISSUE THREAD

**Issue by mikegehard** [vmware-tanzu/community-edition#2134]
**On Page:** [](/docs/latest/aws-install-standalone/)

Under step 5 (Fill out the Standalone Cluster Settings.), we are asked to pick an instance type.

As someone not overly familiar with AWS and completely new to TCE, I would appreciate some help figuring out which one to use from the huge list here:

https://aws.amazon.com/ec2/instance-types/

**Comment by stmcginnis** [comment]
Hey Mike - super open to making this better. Since we can't really document all of AWS's instances, and we don't really know what someone will be running on it once it's deployed, I think it's a little tricky to have much guidance in our docs. To make it even more fun, some types can vary from region to region.

Any suggestions on how we could improve this part?

**Comment by mikegehard** [comment]
What about some wording around what kinds of resources it might take, at least for a development cluster?

**Comment by stmcginnis** [comment]
@kcoriordan - what do you think about adding some wording to this section around choosing the CPU and memory you need based on the type of workloads you expect to be running?

**Comment by stmcginnis** [comment]
Another idea @kcoriordan - what about addressing this and https://github.com/vmware-tanzu/community-edition/issues/2133 by adding another section to the AWS installation docs that gives a very quick overview of how AWS works. In there, we could quickly cover what EC2 is, what their concept of regions means, and some of the considerations when choosing an instance type.

If that works, it would probably make sense to have something similar for Azure too.

**Comment by GrahamDumpleton** [comment]
This has been an issue in TKG for a long time. A suggestion made way back for TKG 1.2 related to this was to at least identify a small subset of instance types that are reasonable defaults and of those which are available in the region where it is deployed at least select one as a default in the installer UI, but with note to click to see more options. Also, since a large number of instance don't usually make sense for clusters, for that subset of reasonable default instance types for typical use case only show those when click on dropdown to show more, unless you have a tick box or something to show the complete list. This would make the experience much better as right now it is too overwhelming when one is presented with too many options.

FWIW, here is another instance where people are finding this all too much.

https://twitter.com/vicnastea/status/1445884081556758528

**Comment by miclettej** [comment]
@qnetter Would you be able to help provide a list of specific AWS instance types that we should expose to users? 

We are thinking that we should offer the user the option to see all instance types (exposed by a toggle or some UI control) but maybe by default we display a much narrower list of instance types. How does this sound?

**Comment by qnetter** [comment]
I'm sure that I can with assistance of a TKG PM... Luckily I'm on that call.

**Comment by miclettej** [comment]
Hi @qnetter checking back to see if there was any outcome from the TKG PM call?

**Comment by qnetter** [comment]
@miclettej no answers yet, just a commitment to work on it...

**Comment by miclettej** [comment]
Hi @qnetter, I have identified the following instance types that use ARM based processors and will go ahead with filtering these out of the AWS instance type lists unless you have any objection:
M6g, T4g, A1, C7g, C6g, C6gn, R6g, X2gd, G5g, Im4gn, Is4gen

**Comment by qnetter** [comment]
@miclettej Agreed - thanks.

**Comment by berndtj** [comment]
I would suggest maybe using a table rather than a dropdown, so that more metadata about the instance types can be presented.  Also the table could be sortable and filterable which would be a huge help.  Currently the worker instance type dropdown is unsorted, which makes is especially hard to use.
