### ISSUE TITLE
Support multiple Infra Providers from a single Management Cluster

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/community-edition#2202]
## Feature Request
Add the ability to have CAPV,CAPZ,CAPA,CAPD, etc. Installed in a single management cluster.

## Describe alternatives you've considered
Management cluster per infra provider

## Additional context
Mgmt cluster per infra provider is a waist of resources.

**Comment by nrb** [comment]
Thanks for this features request!

I think we might be limited by the Cluster API implementations right now, since TCE relies on CAPI.

I'm not super familiar with adding multiple providers into a management cluster, but I do not believe it's currently supported upstream. [This issue in CAPI](https://github.com/kubernetes-sigs/cluster-api/issues/603) was the closest thing I could find to your request.

**Comment by qnetter** [comment]
I'm down with it. I need to sync with others on priority and related questions, though.
