### ISSUE TITLE
ARM64 CLI binaries for linux

### ISSUE THREAD

**Issue by tsrats** [vmware-tanzu/community-edition#2216]
## Feature Request

Would like to formally request arm64 binaries for the Tanzu CLI tools as a first step towards arm64 support. 

## Describe alternatives you've considered
Using x86

## Additional context

**Comment by tsrats** [comment]
Originally from [this request](https://github.com/vmware-tanzu/community-edition/issues/2171)

**Comment by joshrosso** [comment]
Not to maintainers: this will involve build work in both tanzu-framework and community-edition.

**Comment by tsrats** [comment]
Commenting to appease the stale gods.

**Comment by stealthybox** [comment]
Changing the Makefile like so:
```Make
ENVS := linux-arm64
```
(passing ENVS as a makeflag does not work for docker)

Then running
```shell
make release-docker
```

Produces a functional `tanzu` CLI with all of the plugins built for Linux on arm64

I'm able to do a `tanzu uc create tce` similar to the darwin-arm64 build.

It would be good to add this additional ENV so that it shows up in the release build.
