### ISSUE TITLE
Offer minimal deployment model that supports development and experimentation of Tanzu

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#2266]
## Asks

1. Read this proposal
2. [Try out](https://github.com/vmware-tanzu/community-edition/blob/standalone-overhaul/cli/cmd/plugin/standalone-cluster/README.md) the proposed model
3. Vote 👍  or 👎  on this issue
4. If you have additional feedback, respond to this issue

We aim to `accept` or `reject` this proposal 60 days after opening (`12/17/2021`).

## Proposal

⚠️ The name of this feature is currently being determined, you may see it referred to as `local`, `standalone`, and `unmanaged-cluster` in various places. We have decided to move forward with the name `unmanaged-cluster`. Please note that references to `local` or `standalone` (not `standalone-cluster`) represent `unmanaged-cluster`

🚨  This proposal has been partially implemented to help further the conversation around whether we should accept it in this project. [Read here](https://github.com/vmware-tanzu/community-edition/blob/standalone-overhaul/cli/cmd/plugin/standalone-cluster/README.md) for details on how to try it and design details. 🚨

Standalone clusters (SAC) are our attempt to provide workload clusters without the need of a long-running management cluster. With this, we intended to:

* Minimize resource requirements for clusters
* Reduce on boarding time from download to cluster

To accomplish this, we re-purposed Cluster API and extended TKG-Lib (via tanzu-framework) to create the standalone cluster model. With this model in use for many months we've learned that:

1. SAC users often wanted a single-node or local cluster.
1. Users wanting more complex cluster-lifecycle management, need managed clusters.
1. Our usage of cluster-api and tkg-lib created a poor ux for `1` (above) and a stunted experience for `2` (above).
1. Maintaining the functionality support in our dependencies has had significant overhead as it's a use case tangential to our dependencies.

We believe that solving `1` is high-value for those using Tanzu.  We also believe that attempting to replicate cluster-lifecycle management on a single node comes at an inappropriate cost (via dependencies).

**We propose the deprecation of `standalone-cluster` in favor of introducing `local` (clusters).**

## High-level implementation details

In Tanzu, a Management Cluster does the processing of a `TanzuKubernetesRelease` (TKR). It uses the TKR to determine how to create a workload cluster.  

In the `local` model, we'll move the management cluster’s TKR processing client-side. After processing the TKR, we have all the information needed to create a Tanzu [workload] cluster that looks similar to that of one created by a management-cluster. See the following depiction of this relationship.

![image](https://user-images.githubusercontent.com/6200057/137748800-8a116118-1cec-4611-8bd8-bafc49bb6708.png)

As seen above, after parsing the TKR (client-side) and understanding properties of the to-be-created cluster, we can call into a local provider to create a minimal cluster. By leveraging a provider abstraction (interface), we can insulate ourselves from the underlying details of how the infra/host/desktop-env are created. What matters is we receive a kubeconfig with admin access to the API server.

Our initial provider implementation will be `kind` because it's widely accepted in the Kubernetes community. The following gif demonstrates the bootstrap UX for a local Tanzu cluster.

_GIFs are broken up to save file-size_

### Cluster creation:

![1](https://user-images.githubusercontent.com/6200057/137748829-f63968e3-1534-42a4-a3a1-707e6f063f1a.gif)

### Cluster init:

![2](https://user-images.githubusercontent.com/6200057/137748851-171caeff-600f-4f0d-9781-6eefffe71b0b.gif)

### Cluster list / deletion:

![3](https://user-images.githubusercontent.com/6200057/137748872-ffb5de7b-5c7a-4a53-a5ea-3a9d607b92cc.gif)

`local` is good for:

* Workstation use cases of Tanzu
* Minimal (non-prod) resourced use cases of Tanzu
* CI/CD validations atop Tanzu
* Validation of newly created TKRs

`local` is not meant for:

* Cluster-lifecycle simulation
  * For this, use `management-cluster`.

Additionally, this approach would inherently solve many issues we face today:

* Resource utilization would be **drastically reduced**.
* WSL/Docker Desktop could be natively supported.
* Workstation/Host restarts would be supported.
* Added support for running multiple clusters.
* Testing of different component versions (e.g. kapp-controller) would be possible.
* We would delete our fork of `cluster-api` and `tanzu-framework`.

For in-depth implementation details, [please see our PR](https://github.com/vmware-tanzu/community-edition/pull/2257).

## Release Plan

* `0.10.0` will feature this new model alongside the existing `standalone-cluster` model.
* In `0.10.0`, the existing `standalone-cluster` model will print a deprecation notice to the user.
* In `0.11.0`, we'll remove the existing `standalone-cluster` model.

## FAQ

_This section will be updated as questions come in_

* **Q: What about non-local standalone-clusters (AWS, Azure, vSphere)**
  * A: Execution of this proposal **will** cause a gap for AWS, Azure, and vSphere as there will no longer be non-managed clusters available. However, `standalone-cluster`s are essentially very-limited management clusters with a few components ripped out. For users wanting to test and deploy a *single* cluster in one of those environments, we encourage simply creating a management-cluster and scheduling workloads to it. This **is not** our production-ready advise, but can get you the exact functionality (plus some) of the existing standalone-cluster model.

**Comment by dims** [comment]
❤️  this!

**Comment by joshrosso** [comment]
Exactly what @jorgemoralespou said, plus:

* To respect TKRs and spin up a more realistic Tanzu workload cluster, you **still** need to create a workload cluster from the management cluster
    * So this means you need a bootstrap cluster + mgmt cluster + workload cluster to get to where this proposal gets.
* Regarding speed and resources: one of the biggest drivers for this change is how resource intensive CAPD can be. As such, we've helped countless users with bootstrapping issues, which are often rooted in resource constraints.

**Comment by jorgemoralespou** [comment]
I personally don't like Kind and the fact that this proposal misaligns from ClusterAPI, but given the huge different in experience, I have never wanted to use a local standalone cluster but I will definitely use local clusters.

**Comment by vrabbi** [comment]
Also by using kind which has support for things other than docker such as podman it opens capabilities to do such an integration into local clusters if the whole docker desktop licensing thing becomes an issue and people move away from it. Linux isnt an issue in that regard but mac and windows users which i believe would be the vast majority of use cases for TCE local clusters could be benefited by supporting a different container runtime for running the cluster itself.

**Comment by nrb** [comment]
@jorgemoralespou Can you say more about this? What differences specifically?

> reusing the management-cluster for regular use does not work easily because of difference in controllers, etc...

My understanding is the difference between a management cluster and a workload cluster is 3-5 controllers running in the management cluster for the CAPI information. Other than that, I thought they were identical.

Coming from my kubernetes app development background, this would have been very helpful for testing locally against a Kubernetes API server. It would have been less useful for certain constructs (backing up volume data with Velero), but as mentioned above, that was often cloud platform dependent in any case.

**Comment by vincepri** [comment]
Have we thought about creating a Kind provider for Cluster API rather than trying to replicate the lifecycle model?

**Comment by vincepri** [comment]
Thanks for the added context @joshrosso, the above makes. 

When I started reading through the issue from the problem statement it seems that the issues were mostly around speed of standalone cluster execution, have we explored avenues that would help both tkg-lib and cluster-api to create a CAPD (or similar) based cluster in the minimum amount of time possible?

What's the general role of a standalone/local cluster for our users? From our [docs]( https://tanzucommunityedition.io/docs/latest/designs/standalone-clusters): 
> This enables our users to try out many projects and technology in the Tanzu portfolio with a reduced barrier of entry.

Is a kind cluster enough for all use cases? What are the implications of not having an active management-workload cluster in this case?

**Comment by vincepri** [comment]
This all makes sense, thanks folks — it's definitely good to have more context, appreciate all the responses

**Comment by frapposelli** [comment]
The local dev environment use case is different enough from the other "regular" use case that it's ok to have a different lifecycle implementation underneath IMO.

That said, the consumption model should be as aligned as possible to the overall Tanzu consumption model. TKRs in this proposal are an excellent example of this. Still, I would love to see if we could align on things like the new `ClusterClass` managed topology, even if just to describe the cluster you want to provide locally.

**Comment by qnetter** [comment]
@kcoriordan let's discuss what a deprecation notice should look like in docs and where we should insert one now.

**Comment by joshrosso** [comment]
@qnetter we believe we're at a point where this proposal can be **Approved**. We want to make sure you agree and our assumptions are correct.

Here are our assumptions:

* This can be merged into git after `v0.10.0` is released.
* This will be included in our distribution in `v0.11.0`.
* It will be `alpha` in `v0.11.0`.
* The alpha release will **not** feature a UI.
* To promote to beta, a UI is required.

For promotion to beta, we'd create a new proposal describing the UI for standalone.

**Comment by qnetter** [comment]
SGTM with one small reservation.

I’d like a name that can be parallel to other cluster types in terms of ending in -cluster, and we know that cannot be standalone-cluster. To nail this - and if we don’t come up with something better, we can go with what we have now - let’s discuss it in the 1:1 I am rescheduling. Other than that, definitely a go.

Sent from my iPhone

On Dec 8, 2021, at 1:30 PM, joshrosso ***@***.***> wrote:

﻿

@qnetter<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fqnetter&data=04%7C01%7Crklorese%40vmware.com%7C17b8f68401fc40bf97b608d9ba91e2b8%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637745957998040809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vlIeGoUKLTYAJKBVT9nl5Kr1We%2BlDNbd6Hkr16UONqA%3D&reserved=0> we believe we're at a point where this proposal can be Approved. We want to make sure you agree and our assumptions are correct.

Here are our assumptions:

  *   This can be merged into git after v0.10.0 is released.
  *   This will be included in our distribution in v0.11.0.
  *   It will be alpha in v0.11.0.
  *   The alpha release will not feature a UI.
  *   To promote to beta, a UI is required.

For promotion to beta, we'd create a new proposal describing the UI for standalone.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Fcommunity-edition%2Fissues%2F2266%23issuecomment-989211319&data=04%7C01%7Crklorese%40vmware.com%7C17b8f68401fc40bf97b608d9ba91e2b8%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637745957998040809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XpuPIst%2BpVeRVejsMdcUOUiGQkO3LhKKnoWXNh9OSX4%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZWVLYM34UCVOK3BED5JRDUP7E5LANCNFSM5GGYXXSA&data=04%7C01%7Crklorese%40vmware.com%7C17b8f68401fc40bf97b608d9ba91e2b8%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637745957998050775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=G%2FPiEzUMlA3FXLmUvCfZU0Zhvw0LysKkOe9hdWerylc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crklorese%40vmware.com%7C17b8f68401fc40bf97b608d9ba91e2b8%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637745957998060725%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RIkkxOZruMDggUD0kFqB6dIV88FwdKOpyvYX98vmLHY%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crklorese%40vmware.com%7C17b8f68401fc40bf97b608d9ba91e2b8%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637745957998060725%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VASFaXRVb1qFVKteZcTlt8EuWbvVll2%2FhARHhbqwBKk%3D&reserved=0>.

**Comment by jpmcb** [comment]
> To accomplish this, we re-purposed Cluster API and extended TKG-Lib (via tanzu-framework) to create the standalone cluster model.

FYI - when we move forward with this proposal, the TCE team will delete unneeded dev dependencies that were used to build the _old_ standalone cluster model. This includes the `tce-main` branch in `tanzu-framework` and the Cluster API fork we created.

**Comment by jorgemoralespou** [comment]
Reading above description and knowing that Roger wants a name, I decided to through here some options:
- dev-cluster
- minimal-cluster, mini-cluster
- single-cluster
- local-cluster
- standalone-cluster (seems Roger don't want this, but still I think it's an option)
- ephemeral-cluster
- unmanaged-cluster
- nano-cluster
- bare-cluster

**Comment by qnetter** [comment]
The reason I don’t want standalone-cluster is that when you add the new thing to 0.9.1 or 0.10.0 you would have the same name for both…

--
Roger Klorese (They/Them or He/Him)
Product Line Manager
***@***.***
***@***.***%0b>Office: 425.709.5248
Mobile: 425.444.5493

[VMware]<http://www.vmware.com/>


From: Jorge Morales Pou ***@***.***>
Date: Thursday, December 9, 2021 at 11:08 AM
To: vmware-tanzu/community-edition ***@***.***>
Cc: Roger Klorese ***@***.***>, Mention ***@***.***>
Subject: Re: [vmware-tanzu/community-edition] Proposal: Replace `tanzu standalone-cluster` model with `tanzu standalone` model (Issue #2266)

Reading above description and knowing that Roger wants a name, I decided to through here some options:

  *   dev-cluster
  *   minimal-cluster, mini-cluster
  *   single-cluster
  *   local-cluster
  *   standalone-cluster (seems Roger don't want this, but still I think it's an option)
  *   ephemeral-cluster
  *   unmanaged-cluster
  *   nano-cluster
  *   bare-cluster

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Fcommunity-edition%2Fissues%2F2266%23issuecomment-990140805&data=04%7C01%7Crklorese%40vmware.com%7C4015f31f691e4e54a7c108d9bb4738f1%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637746736846125946%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q6mQQ3JvlqKJwvuByLm71ATwLTIpE4XPUfp9D%2BBsltY%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZWVL2CV6LJAROCKNOVD5LUQD5BDANCNFSM5GGYXXSA&data=04%7C01%7Crklorese%40vmware.com%7C4015f31f691e4e54a7c108d9bb4738f1%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637746736846135898%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TJz%2FD4BILuJQnoaN3O8YBb6bt3Pl7wNVtTiLwOW%2BcSQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crklorese%40vmware.com%7C4015f31f691e4e54a7c108d9bb4738f1%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637746736846145855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oqF%2BQBKRZLs7LU2qqIEGGLXmR9gMhtWMxt%2F5tIA0%2BIM%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crklorese%40vmware.com%7C4015f31f691e4e54a7c108d9bb4738f1%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637746736846155815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XD5ZiEcIgu6GUGMl92ZpxxjQn7OgmQSg3agdt6yB%2BIA%3D&reserved=0>.

**Comment by jorgemoralespou** [comment]
Agree, although selecting the same name would help to fast path to removal of the old feature :-D

**Comment by qnetter** [comment]
Also, I like:

  *   minimal-cluster, mini-cluster
  *   local-cluster
  *   unmanaged-cluster

--
Roger Klorese (They/Them or He/Him)
Product Line Manager
***@***.***
***@***.***%0b>Office: 425.709.5248
Mobile: 425.444.5493

[VMware]<http://www.vmware.com/>


From: Jorge Morales Pou ***@***.***>
Date: Thursday, December 9, 2021 at 11:08 AM
To: vmware-tanzu/community-edition ***@***.***>
Cc: Roger Klorese ***@***.***>, Mention ***@***.***>
Subject: Re: [vmware-tanzu/community-edition] Proposal: Replace `tanzu standalone-cluster` model with `tanzu standalone` model (Issue #2266)

Reading above description and knowing that Roger wants a name, I decided to through here some options:

  *   dev-cluster
  *   minimal-cluster, mini-cluster
  *   single-cluster
  *   local-cluster
  *   standalone-cluster (seems Roger don't want this, but still I think it's an option)
  *   ephemeral-cluster
  *   unmanaged-cluster
  *   nano-cluster
  *   bare-cluster

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Fcommunity-edition%2Fissues%2F2266%23issuecomment-990140805&data=04%7C01%7Crklorese%40vmware.com%7C4015f31f691e4e54a7c108d9bb4738f1%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637746736846125946%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q6mQQ3JvlqKJwvuByLm71ATwLTIpE4XPUfp9D%2BBsltY%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZWVL2CV6LJAROCKNOVD5LUQD5BDANCNFSM5GGYXXSA&data=04%7C01%7Crklorese%40vmware.com%7C4015f31f691e4e54a7c108d9bb4738f1%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637746736846135898%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TJz%2FD4BILuJQnoaN3O8YBb6bt3Pl7wNVtTiLwOW%2BcSQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crklorese%40vmware.com%7C4015f31f691e4e54a7c108d9bb4738f1%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637746736846145855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oqF%2BQBKRZLs7LU2qqIEGGLXmR9gMhtWMxt%2F5tIA0%2BIM%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crklorese%40vmware.com%7C4015f31f691e4e54a7c108d9bb4738f1%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637746736846155815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XD5ZiEcIgu6GUGMl92ZpxxjQn7OgmQSg3agdt6yB%2BIA%3D&reserved=0>.

**Comment by qnetter** [comment]
I forget, @joshrosso , if the new model requires that the cluster be local to the plugin on any as-yet-unbuilt backend...

**Comment by joshrosso** [comment]
>  if the new model requires that the cluster be local to the plugin on any as-yet-unbuilt backend

This model does not *require* the cluster be local to the plugin.

**Comment by vrabbi** [comment]
I oersinally like the name standalone and think it is the best option from a naming perspective if that name cant/shuldnt be reused i think the most accurate and understandable name would be unmanaged-cluster as it would make sense both for the current kind implementation as well as what had been brought up in terms of the idea to bring any cluster and "tanzuify" it.

**Comment by qnetter** [comment]
@joshrosso suggested static-cluster, which directly addresses the lack of LCM, and that is where we are going.

**Comment by jorgemoralespou** [comment]
When I heard static cluster last thing I could think of is on  the lack of LCM but rather a cluster that can't be changed, resized,... 😔

**Comment by joefitzgerald** [comment]
It feels like we are really overthinking this. `standalone` or `local` both match my expectations, but tacking on `-cluster` just for uniformity with non-local clusters seems quite awkward.

I think we want lots of people to use this, and so simplicity & brevity should come above uniformity with plugins focused on completely different deployment models. It is not insane to prioritize a low number of keystrokes.

**Comment by stmcginnis** [comment]
Another vote in favor of keeping to the standalone naming. I did like `local`, but while that fits really well right now with only local docker support, that may not be a good name if/when we add support for additional providers.

Some of my favorites, in order of current preference:
- single-cluster
- independent-cluster
- active-cluster
- solo-cluster
- quick-cluster
- dev-cluster

**Comment by cantbewong** [comment]
If it is not the same as the original standalone I am against re-using that name. Creates risk people find old presentations, blog posts - assume it is valid and get confused.

I like ephemeral, or maybe thiese are too colloquial, but "burner cluster" or "disposable cluster"

**Comment by dvonthenen** [comment]
I don't like `static-cluster` either. When I hear the name, it sounds like it's a cluster that gets deployed but that is "static" and something that doesn't change or could be changed (ie deploying pods, changing cluster configurations/state, etc). Sounds more like a "reference" implementation of cluster or something.

`standalone-cluster` seems ok to me but I do get the point of reusing the name and it leading to confusion. My top choices are in order of preference:
- ephemeral-cluster
- independent-cluster
- dev-cluster

**Comment by qnetter** [comment]
I'd like to call it `unmanaged-cluster` because:
- It is a good counterpoint to `management-cluster`
- It reflects the fact that clusters can be attached, but not registered or lifecycle-managed, with Tanzu Mission Control

**Comment by nrb** [comment]
I'd echo Jorge's sentiments about the name `static`; on first reading, it didn't speak to lifecycle to me, but rather a Kubernetes cluster that was immutable.

I understand the reticence on re-using `standalone-cluster`. However, I'd like to ask - what is wrong with using a version to signal it's different? At a high level concept, it's similar in goal, just with a different implementation. Semantic versioning would indicate that it is incompatible, though we do run into the major versions being generally understood as stable.

If folks are adamant on a rename instead of incrementing the version, I like the following

* `unmanaged`, to clearly communicate it does not require a management cluster
* `ephemeral`, to clearly communicate it is not intended to be long-lived/lifecycle-managed.
* `independent` for similar reasons to `unmanaged`

**Comment by jorgemoralespou** [comment]
Copying from Tanzu community edition docs (https://tanzucommunityedition.io/docs/latest/getting-started-standalone/).

> 🚨 Warning 🚨 

Standalone clusters are highly-experimental and partially implemented! Functions such as scaling clusters are not implemented. If you follow this guide, you may need to clean-up resources created by these clusters manually!

With this warning in place I would consider changing the implementation something that any user would understand and not complain. I don't think the change would break anyone really.

**Comment by joshrosso** [comment]
Thanks everyone for your input ❤️!

Talked to @qnetter today and there are 2 **final** items they own to get this to `proposal/accepted`.

1. The *official* call on the name we're going with.
1. Given the delay of `0.10.0`, should we ship this new model alongside the existing `standalone-cluster` model[0].


[0]: _This assumes we do not re-use the name `standalone`, which my understanding is we have decided against._

**Comment by joshrosso** [comment]
Spoke with @qnetter today and regarding `2`, we are going to ship this new model alongside `standalone-cluster` (existing model) in the `0.10.0` release.

Naming decision will be made by @qnetter in ~24 hours.

**Comment by joshrosso** [comment]
A few updates:

* The decided on name is `unmanaged-cluster`.
* This proposal is *approved*.
* In our `0.10.0` release, this model will be available alongside the existing `standalone-cluster` model
* The existing `standalone-cluster` model output a deprecation warning to users.

**Comment by garrying** [comment]
Minor feedback/thought on the terminal experience of the [proof-of-concept](https://github.com/vmware-tanzu/community-edition/blob/standalone-overhaul/cli/cmd/plugin/standalone-cluster/README.md) given it is introducing newish output patterns: The secondary text could get difficult to read depending on the minimum contrast config of the terminal and users' color scheme. For example, on Solarize, the text is barely visible. ![Screen Shot 2022-01-04 at 4 52 58 PM](https://user-images.githubusercontent.com/227587/148128772-e0527ae2-66e5-4acb-b1e0-16110b15988d.png)

Related: https://github.com/vmware-tanzu/community-edition/issues/2730 where we're starting to think about improving visibility of processes.

**Comment by stmcginnis** [comment]
The color formatting looks great... when we are running in a terminal theme that fits well with it. But it's hard to guarantee that, so I think we should either see if we can find some way to query the terminal to get color recommendations based on the theme, or we should just go with the default color and just use indentation to make it easier to read.

There may also be some color-blind concerns with the way we are doing it now as well.

**Comment by joshrosso** [comment]
> or we should just go with the default color and just use indentation to make it easier to read.

^this. The indentation is adequate.

**Comment by jpmcb** [comment]
A few thoughts on the color / contrast problem:

- We should follow the `$NO_COLOR` env variable standard and disable colors if that is present: https://no-color.org/
- We should also check for if the terminal doesn't support colors. We should be able to inspect this via `$TERM` == `dumb` 
- And we should check if the terminal is a TTY terminal (we _might_ already be doing this ..)
- It wouldn't be a bad idea to introduce a color library so that we aren't using raw escape characters to create colors in our code. Something like: https://github.com/fatih/color
  - I don't _think_ there's a way to inspect the terminals color palate and dynamically set the colors based on what the user is using. But I believe using a color library would enable us to set common sets of colors that should be supported by _most_ color themes (or at least the popular ones) and avoid some of the poor contrast issues we've created. I agree the indentation is adequate for understanding the UX flow and if someone really doesn't want the colors, they could set the flag in the command or use `$NO_COLOR` (when/if we implement that)
- All in all however, this shouldn't block this getting out to users since it's possible to bypass the colors entirely. All of the above would be user experience enhancements to an already working UX.

**Comment by kartiklunkad26** [comment]
How would the docs look like for unmanaged-cluster in the context of existing documentation? Haven't really seen anything for docs in the proposal?

**Comment by kcoriordan** [comment]
I'm looking at this today, and tracking here: https://github.com/vmware-tanzu/community-edition/issues/2808

**Comment by garrying** [comment]
The links to proposed model are pointing to an empty README. For posterity, here's a link to the original README contents: https://github.com/vmware-tanzu/community-edition/blob/db06202fdd79271e4b5e80a0aa76387ca78917f0/cli/cmd/plugin/standalone-cluster/README.md
