### ISSUE TITLE
Repeatly create management cluster VM when deploying TCE in vSphere

### ISSUE THREAD

**Issue by Cupido10** [vmware-tanzu/community-edition#2497]
Hi all, I’ve tried to deploy Tanzu Community Edition (TCE) on vSphere without Avi LB and the problem is the vcenter will repeatly create the same master node (Single Control Plane Node) and worker node during the phase of “Create management cluster”. I’m using Ubuntu 20.04 as my bootstrap machine and I found that this repeated behavior will be stopped until I poweroff the bootstrap machine. Any thoughts on this problem? Thanks!

**Comment by stmcginnis** [comment]
Additional discussion in Slack can be found here: https://kubernetes.slack.com/archives/C02GY94A8KT/p1636561590442800

We need to get the capv-controller logs to see why it is failing and retrying.

**Comment by stmcginnis** [comment]
Assuming this has been resolved. This behavior sounds like it was trying to reconcile the desired state, but hitting some sort of error. Slack thread is unresolved, but it was left at the need to get the logs of the capv-controller. We've since added some debug steps here that can be used to find these logs to troubleshoot:

https://tanzucommunityedition.io/docs/latest/tsg-bootstrap/#troubleshooting-manually

Please feel free to reopen with additional information if this is still an issue.
