### ISSUE TITLE
How do I update my CSI driver in a workload cluster?

### ISSUE THREAD

**Issue by jakerobinson** [vmware-tanzu/community-edition#2684]
## Description

I want to take advantage of the volume snapshot capability in the new version of the vSphere CSI (2.4.0). I cannot find any documentation on how to determine the CSI version running in my current clusters. (I know how to do this now.)

With the lack of documentation in TCE, I followed the documentation provided by the VMware Docs CSI installation, which did not work. TCE does not install the CSI the same way they recommend in their docs.

After attempting to delete the CSI package, packageinstalls, etc from the workload cluster, it appears the management cluster redeploys everything that I just deleted. I was not expecting this.

From what I've learned now from the awesome folks on Slack, It appears there should be a more 'Tanzu' way to do upgrades of components, but I cannot find this particular documentation.

**Comment by joshrosso** [comment]
Hey @jakerobinson!

> TCE does not install the CSI the same way they recommend in their docs

Can you tell us in what way(s) it is being installed in an non-recommended way? If things are being done out of practice, we can request changes from the @vmware-tanzu/pkg-vsphere-csi-owners.

> I want to take advantage of the volume snapshot capability in the new version of the vSphere CSI (2.4.0)

Lower-level components like CSI/CNI/etc are all bound to an official release, which we refer to as a Tanzu Kubernetes Release (TKr). This means the only **supported** way to do this is to wait for a new release where we publish a new TKr. I don't have an exact timeframe for when this will be included as we're still getting our ducks-in-a-row as a new project and trying to figure out details on how we publish these updates (and support compatibility).

Additionally, we're working on a proposal #2717  which will enable you to modify TKrs such that you can test your own "release" with different versions of components, like CSI-plugins. But this is a long-term effort.

> After attempting to delete the CSI package, packageinstalls, etc from the workload cluster, it appears the management cluster redeploys everything that I just deleted. I was not expecting this.

The best workaround for now is likely this, to tell Tanzu to stop trying to manage the CSI component so that you can install and manage your own.

There are a few level of reconciliation/ownership to resolve here.

I'm spinning up a vSphere-based cluster now to give you some exact steps.

**Comment by joshrosso** [comment]
The reason you're seeing the re-creation of the CSI workload is due to the addons-manager-controller (management-cluster) re-creating the `PackageInstall` declaration in the workload cluster. Here's a visual representation of this:

![image](https://user-images.githubusercontent.com/6200057/150219484-66e78972-276d-47aa-8b7a-a95d940e848d.png)

## To stop this so that you can install you own CSI:

1. **From the management-cluster**, pause the reconciliation of the CSI addon.

    ```sh
     kubectl patch secret/<cluster-name>-vsphere-csi-addon \
         -p '{"metadata":{"annotations":{"tkg.tanzu.vmware.com/addon-paused": ""}}}' \
         --type=merge
    ```
    
    > be sure to replace cluster name.


2. **From the workload cluster**, delete the CSI package install.

    ```sh
    kubectl delete packageinstalls -n tkg-system vsphere-csi
    ```

**Comment by vijaykatam** [comment]
> I want to take advantage of the volume snapshot capability in the new version of the vSphere CSI (2.4.0)

Are you asking about [this](https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/docs/book/features/volume_snapshot.md#how-to-enable-volume-snapshot--restore-feature-in-vsphere-csi-)? Looks like it is an alpha feature and we currently don't support it out of the box. 

@joshrosso's method above should allow you to pause the reconcile so that you can manually patch `configmap/internal-feature-states.csi.vsphere.vmware.com`

**Comment by joshrosso** [comment]
@jakerobinson did you have a chance to try this out?

**Comment by jakerobinson** [comment]
All good, @joshrosso! Thanks for the info!
