### ISSUE TITLE
[Docs] [](/docs/latest/package-management/)

### ISSUE THREAD

**Issue by danielhelfand** [vmware-tanzu/community-edition#2774]
## Description

The PackageRepository tag (i.e. `projects.registry.vmware.com/tce/main:0.9.1`) mentioned in the docs [here](https://tanzucommunityedition.io/docs/latest/package-management/) seems to be out of date with the Package versions mentioned in the docs. 

Wondering if the tag should be 0.10.0 instead of 0.9.1? This seems to pull in the correct Package versions that match the current docs.

## Additional Context

I am installing the PackageRepository without using the tanzu cli. Just using a PackageRepository resource that references the above bundle.

**Comment by stmcginnis** [comment]
I _think_ this may be a side effect due to our lack of versioned docs so far. The currently released version of TCE is v0.9.1, but there have been updated merged in to the repo for our next (v0.10.0) release. Prior to that release, but after the next package tag is created, the docs should be updated to point to the new `main:0.10.0`.

@seemiller - can you confirm?

**Comment by joshrosso** [comment]
Please re-open if there's any follow-up needed.

At this point, docs should always reference `0.9.1` as its the only thing we've released (while technically `0.10.0` is discoverable, it's not released).
