### ISSUE TITLE
[Docs] [Kubernetes Platform Documentation | Tanzu Community Edition](/docs/latest/)

### ISSUE THREAD

**Issue by m2si-mmo** [vmware-tanzu/community-edition#2807]
## Description

 Cannot install TCE on a MacBook Pro 2018
<img width="1674" alt="tanzu" src="https://user-images.githubusercontent.com/47722866/148920322-7aac7973-4879-4cfa-9b3d-6403a366a1c9.png">

**Comment by stmcginnis** [comment]
Hi @m2si-mmo - we'll need to check some logs, but first there is a common issue folks have been hitting that might be a quick easy check for us to do.

The current release of TCE does not work with cgroupv2, but recent releases of Docker Desktop (as of v4.3.0 I believe) have moved to using it. Can you run `docker info | grep Cgroup` and see if there is a line returned that says "Cgroup version: 2"?

If that is the case, the only fix at this point is to downgrade Docker Desktop to a version prior to that switch.

**Comment by m2si-mmo** [comment]
Indeed I'm using the last version of Docker Desktop for Mac. 
Can you tell me to which version should I downgrade to ?
Regards

**Comment by stmcginnis** [comment]
The cgroupv2 change was in the [4.3.0 release](https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-430), so any version prior to that should work. It looks like 4.2.0 was the last release prior to that.

**Comment by m2si-mmo** [comment]
It works now on my Mac but getting n issue with the kappa-controller pod, I got an ImagePullBackOff.
trying to fix it

**Comment by stmcginnis** [comment]
Hey @m2si-mmo - just curious if things ever started working for you. If you get a chance, please let me know. Thanks!

**Comment by m2si-mmo** [comment]
Hi,

it's working well with the 3.6 version. Did you know when the ARM will be supported ?

**Comment by stmcginnis** [comment]
> it's working well with the 3.6 version.

Excellent!

> Did you know when the ARM will be supported ?

You may want to watch this issue: https://github.com/vmware-tanzu/community-edition/issues/2171

We can build ARM clients today, but I think most folks are looking for ARM deployments. In other works, you can use the `tanzu` CLI to create clusters on ARM today, but only if you are deploying the cluster to an amd64 environment.

We would like to be able to deploy on ARM environments, but basically we are waiting for upstream images to become available to do so. I have seen working going on towards that end, but since there are several pieces that get pulled in to create a cluster, it might be some time yet before we have a fully working solution for ARM environments.

Going to close this issue, but please comment on 2171 or open another issue if there are any other problems you run in to. Thanks!
