### ISSUE TITLE
unmanaged-cluster: Downloading TKR re-prints log message rather than showing progress `.` characters

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#2852]
## Bug Report

From a comment in another PR (https://github.com/vmware-tanzu/community-edition/pull/2822#issuecomment-1012618133)

![image](https://user-images.githubusercontent.com/6200057/149545920-0e5fcdbc-799d-4f6a-9940-acc9664a677e.png)

## Expected Behavior

For a carriage return `\r` to replace this line, giving the visualization of progress.

## Steps to Reproduce the Bug

Remove the locally downloaded TKR then run a cluster create.

**Comment by joshrosso** [comment]
Nice to have for alpha release v0.10.0; but not required until v0.11.0.

**Comment by jpmcb** [comment]
Hmmm I'm having trouble reproducing this.

@garrying, it'd be helpful to get a dump of information on:
- the terminal you're using / OS / environment
- the output of `echo $SHELL`
- the output of `echo $TERM`
- if you're using 256 term colors
- maybe your shell .rc file

And just to confirm, this is only happening for the download step?

**Comment by garrying** [comment]
- `macOS 11.6.2`, iTerm 2 (3.4.15)
  -  [.zshrc](https://gist.github.com/garrying/47f89b4ae05aa0b2fa48641a2565b8d2)
- `Ubuntu 20.04.3 LTS`, Hyper (3.1.5)
- on both:
  - `/bin/zsh`, `/usr/bin/zsh`
  - `xterm-256color`

Yeah, it's only happening on download step. Interesting, I'm not seeing the issue on `macOS 12.1` and I have a similar setup on it.

**Comment by jpmcb** [comment]
Hmmmm still not able to reproduce on mac with iTerm or the default terminal, in different shells, on my linux desktop, or in a virtual machine.

Just so we're all working off the same binary here (since it's yet released), let's connect on K8s slack and I can drop you a newly built binary to try

**Comment by jpmcb** [comment]
Ahhhhh I think I see what's happening. Here's how I've been able to reproduce it:

---

First, remove the existing bom so it initiates a download again
```
$ rm -rf ~/.config/tanzu/unmanaged
```

Run a create which should end the download logging animation loop:
```
unmanaged-cluster create my-cluster
```

---

In a _wide_ terminal window, this is the expected result:
![Screen Shot 2022-01-24 at 11 43 09 AM](https://user-images.githubusercontent.com/23109390/150844349-94b39bec-f46a-4301-a3e6-c7261354f797.png)

In a more _narrow_ terminal, the terminal prompt is wrapping to the next line ... so it has no line to replace:
![Screen Shot 2022-01-24 at 11 42 20 AM](https://user-images.githubusercontent.com/23109390/150844232-f7469612-9470-47f6-a180-b586fd8a384b.png)

This is probably why I couldn't reproduce it ... my monitor is too wide 😂 

This is especially troublesome since we pad the carriage return in `RepalceLinef` with a bunch of empty spaces. I'm not sure there's a great solution here (or why this was necessary to do in the first place) but it might be worth exploring removing that extra space.

https://github.com/vmware-tanzu/community-edition/blob/826f80e75acec4dda039cc489d06e35d89fbc49f/cli/cmd/plugin/unmanaged-cluster/log/log.go#L271-L273
