### ISSUE TITLE
[unmanaged-cluster] Save Kind config in the Kind cluster

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#3061]
## Feature Request
For troubleshooting purposes it would be ideal to see the kind configuration that was created. This configuration is now managed in memory while creating the cluster, but it'll be ideal that this information was persisted somewhere. I would think that since this is not an important file to have on the local system it can be saved within the cluster, on the cluster's filesystem on a well known location so that if needed it can be queried.

## Additional context
https://kubernetes.slack.com/archives/C02GY94A8KT/p1644252973882599

**Comment by jpmcb** [comment]
I think this feature request would introduce alot of unnecessary complexity in order to store the `kind` yaml config on the cluster. We would need to have either a storage solution installed on the cluster that can accept the file or a custom CRD that can consume the yaml. 

Further, I don't think this would be very discoverable by users. We already have the precedence that configs are stored on the local filesystem.

**_Alternative_**: for simplicity, let's store the `kindConfig.yml` file where we place our other configurations on the local filesystem under:

```
~/.config/tanzu/tkg/unmanaged/{CLUSTER-NAME}/
```

**Comment by jpmcb** [comment]
> two storage areas (dirs) for files that are relevant/to be used

Good point! That directory is already irrelevant and doesn't hold anything useful. Right now, it has the
- bootstrapping logs
- the unmanaged-cluster config that was used in bootstrapping
- the kube.conf that gets merged into the users `~/.kube/config`
So I think placing another file directly there works for now 👍🏼
