### ISSUE TITLE
Creation of managed cluster fails

### ISSUE THREAD

**Issue by minuq** [vmware-tanzu/community-edition#3200]
## Bug Report

Following the [getting started](https://tanzucommunityedition.io/docs/latest/getting-started/) guide, the management-cluster creation fails at `Waiting for cert-manager to be available...`. 

## Expected Behavior

Cluster to be created and starting.

## Steps to Reproduce the Bug

Follow the guide for Linux, Docker until step "Local Docker Bootstrapping" `tanzu management-cluster create`

## Screenshots or additional information and context
- exec into the control plane, execute `kubectl get pods -A`, locate faulty pod. (Screenshot 1)
- `kubectl describe pods -n kube-system kindnet-rncqq` (Screenshot 2) 
That error is not _that_ surprising since the folder doesn't exist. After creating `kindnet-cni` in said folder it gets filled with the expected files. (Screenshot 3)

Even after doing so, the pod still fails to start with the same error message. 

`kind create cluster` works just fine (using the kindnet image `docker.io/kindest/kindnetd:v20210326-1e038dc5` instead) as well as `tanzu unmanaged-cluster create`.
![image](https://user-images.githubusercontent.com/460656/154858486-2d0a3d9e-9159-4c27-ac3a-a5bc4a643846.png)
![image](https://user-images.githubusercontent.com/460656/154858522-cca64467-3733-460f-8681-9de01200612a.png)
![image](https://user-images.githubusercontent.com/460656/154858716-1d568b7d-cb66-42fc-9a84-85b13d934a72.png)

## Environment Details

* Build version (`tanzu version`): v0.10.1 / v0.9.1
* Deployment (Managed/Standalone cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker (cgroupfsv1)
* Operating System (client): EndeavourOS
* Kernel: 5.16.10-arch1-1 with cgroupv1 enabled, ipv4 forwarding as per #2138 #2150

## Diagnostics and log bundle

[here](https://github.com/vmware-tanzu/community-edition/issues/3200#issuecomment-1046327147)

**Comment by stmcginnis** [comment]
Thanks for reporting this!

Can you run through the troubleshooting steps here: https://tanzucommunityedition.io/docs/latest/tsg-bootstrap/

I've seen occasional timeouts pulling down images, so it's possible this is just one of those transient errors and it could work well if you tried again later. But we would need to see some of the logs to understand what is happening with cert-manager.

**Comment by minuq** [comment]
[bootstrap.tkg-kind-c89b0sgg348drglfddo0.diagnostics.tar.gz](https://github.com/vmware-tanzu/community-edition/files/8104966/bootstrap.tkg-kind-c89b0sgg348drglfddo0.diagnostics.tar.gz)

**Comment by mylesagray** [comment]
@stmcginnis FWIW, I was working with @minuq on this, and the `kubenet` container is consistently failing in TCE mgmt cluster with some kind of weird memory cgroup problem (detail above).

Docker daemon running in cgroup v1 mode.

The same doesn’t occur with a vanilla kind cluster running on the same Docker env.

Additionally, unmanaged TCE clusters, that use antrea instead of kubenet are not affected and deploy correctly. The problem seems to be specific to the 0.5.4 version of kindnet we ship.

**Comment by minuq** [comment]
I tried https://github.com/vmware-tanzu/community-edition/releases/tag/v0.11.0-rc.1 yesterday, which solved this issue (and uses `docker.io/kindest/kindnetd:v20210326-1e038dc5`, which might be the reason for it?)

**Comment by joshrosso** [comment]
The `kind` image, prior to `v0.11.*`, was built with an **extremely** old version of `kind`. If it works in `v0.11.0-rc.1`, likely worth closing this issue.

side-note: Unlike managed clusters, unmanaged clusters built their images with a modern version of `kind`, so that may explain why they were unimpacted.

@minuq let us know if there's any more follow-up needed or if you're ok with closing this issue.

Thanks everyone!

**Comment by minuq** [comment]
Sure thing, thanks for the quick solution.
