### ISSUE TITLE
Support `unmanaged-cluster` profiles

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#3537]
## Feature Request

Users want the ability to specify a one line bootstrap command that will install a opinionated set of packages/configurations.

A solid UX for `unmanaged-cluster`, and then IMO, managed clusters, would be to offer a specification of a profile.

```
tanzu uc create --profile=serverless
```

under the hood, a `profile` could simply map to a metapackage, which satisfies this need.

For further context, see: https://github.com/vmware-tanzu/community-edition/issues/3458#issuecomment-1063178534

**Comment by jpmcb** [comment]
Similar issue for management clusters:
- https://github.com/vmware-tanzu/tanzu-framework/issues/1660

and for workload clusters:
- https://github.com/vmware-tanzu/community-edition/issues/322

**Comment by joshrosso** [comment]
`--profile` should map to a package or arbitrary set of packages. Meaning, initially, this should simply instruct that:

1. A set of packages can be specified to be installed at bootstrap time.
2. Values files can be provided for each package that is bootstrapped.
3. When `--profile` is set, the install should block and wait for the user-managed package repo to reconcile before continuing
4. After 3 completes, it should create the relevant package installs in the cluster.

Initially, we'll give this work to me and re-assess as we progress.

**Comment by jorgemoralespou** [comment]
One important thing to consider is that when installing packages, most of them require some config to work fine in a specific environment and with the user's needs. It's not the same configuration you provide when installing a cluster locally (in your docker provider) than when installing a cluster on another infrastructure provider (AWS, Azure, vSphere) and not even are the same packages needed in these different infrastructure providers even for the same use case.

Currently, I see 2 gaps:
- We don't provide a default configuration for many packages that just work (specially for the docker provider)
- Carvel does not support any intelligence (or query of the cluster https://github.com/vmware-tanzu/carvel-kapp-controller/issues/410) to understand the Capabilities it provides or the infrastructure provider in use, so that could make a decision on what and how to install things. This could be addressed at this point by TCE team and the packages we create and have some logic previous to deploying onto the cluster, but that would add additional toil for the packaging teams and for TCE team, while the appropriate route is to improve kapp-controller's capabilities.

I'd be happy to get involved (review, brainstorm, discuss, test, anything...) for this feature.

**Comment by joshrosso** [comment]
@jpmcb and I had a session today to talk about this initially, pasting some of the thoughts here for reference:

![image](https://user-images.githubusercontent.com/6200057/160869224-6ddc790e-6881-44dd-ab52-b15738c857b2.png)

![image](https://user-images.githubusercontent.com/6200057/160869271-2f9067bf-008e-4ffa-84e9-2a925c438e32.png)

**Comment by jorgemoralespou** [comment]
@jpmcb @joshrosso some quick comments after looking at the pictures above:
- Packages currently have long names. So it would be more like `tanzu uc create --profile apk.community.tanzu.vmware.com --profile-config=values.yaml`
