### ISSUE TITLE
Isssue with doc preview in PRs

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#3667]
## Description

Issue with netlify doc preview url in PRs
#related: https://github.com/vmware-tanzu/community-edition/pull/3656, https://github.com/vmware-tanzu/community-edition/pull/3643, https://github.com/vmware-tanzu/community-edition/pull/3637, https://github.com/vmware-tanzu/community-edition/pull/3490, https://github.com/vmware-tanzu/community-edition/pull/3558

Preview link defaults to `v0.10` - should this be `edge`?
Updates not appearing/appearing incorrectly

for example:
https://github.com/vmware-tanzu/community-edition/pull/3665
I would expect to see the update here:
https://deploy-preview-3665--quirky-franklin-8969be.netlify.app/docs/edge/getting-started-unmanaged/
or for
https://github.com/vmware-tanzu/community-edition/pull/3666
I can see the new file in the toc under Guides here but when I click on it, it redirects to `v0.10/`:
https://deploy-preview-3666--quirky-franklin-8969be.netlify.app/docs/edge/

**Comment by stmcginnis** [comment]
My assumption was that the docs build script would change the `docs_latest` setting, but that does not appear to be the case. Due to that, all `include` files are getting set to the "current" release of v0.10.0 here:

https://github.com/vmware-tanzu/community-edition/blob/40f599ad74e73f3aba3f94b93601e966770353b0/docs/site/layouts/shortcodes/include.html#L2

Jonas pointed to https://github.com/vmware-tanzu/community-edition/blob/main/docs/site/themes/template/layouts/partials/docs-sidebar.html#L6 where versioning is handled for the sidebar, or possibly using `CurrentSection.Params` to get the version.

Will need to investigate some more and figure out the "more correct" approach to get this value.
