### ISSUE TITLE
:bulb: Deliver tanzu as a "Oh My ZSH!" plugin (for an even better console UX) :pray: 

### ISSUE THREAD

**Issue by adriens** [vmware-tanzu/community-edition#3759]
# :point_right: Context

[Oh My ZSH!](https://ohmyz.sh/) is a very widely used `zsh` theme that make the console experience very efficient and comfortable.

It provides an ever growing set of [plugins](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins) for the most famous softwares.

A plugins provvided in particular : 

- A set of commonly used aliases
- Auto complete experience

It provides in particular plugins around `K8S`(& `Docker`) ecosystem like : 

- brew
- docker
- docker-compose
- helm
- [kn](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/kn)
- kubectl
- [kubectx](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/kubectx)
- [kube-ps1](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/kube-ps1)
- microk8s
- minikube

# :bulb: The idea

As for `minikube` or `microk8s` it would make sense to get the [`Tanzu CLI`](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.3/vmware-tanzu-kubernetes-grid-13/GUID-tanzu-cli-reference.html) as a plugin to make : 

- its use even smoother
- `Tanzu` better known as part of an awesome console experience (better screencasts for example for bloggers, ...)  : could help for  #3295

# :white_check_mark: Actions

- [ ] Make a feedback on this idea
- [ ] Submit a PR to [`OH MY ZSH!`](https://github.com/ohmyzsh/ohmyzsh) so `tanzu` cli gets an amazing support
- [ ] Once PR merged, make an announcement and ideally a little demo about that

**Comment by jpmcb** [comment]
Very cool idea! I've used OMZ for years and it's a great framework for managing your zsh environment and themes. 

The community can definitely do this but a few questions first:

> A set of commonly used aliases

Do we already know about these or have an idea of what people would want here?

> Auto complete experience

FYI - there hasn't been alot of work that's gone into the completions. We get _alot_ for free from using `cobra` but since `tanzu` uses and consumes various other `cobra` plugins, this may be tricky.

**_If users are experience usability issues,_** we should focus on fixing them at the root first instead of attempting to wrap a shell framework around it. We also don't want to leave users of `bash`, `fish`, etc out of loop.

Looks like [`minikube`](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/minikube/minikube.plugin.zsh), [`helm`](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/helm/helm.plugin.zsh) etc are mostly using OMZ for getting completions in automatically

**Comment by adriens** [comment]
Hi @jpmcb ,

I'll use every day more and more the `tanzu` cli with my team. So for now, I don't really which aliases could be created (which commony tasks could be aliased). : maube creation.drop tasks.
