### ISSUE TITLE
Implement standalone cluster BOM reduction

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#389]
## Feature Request

Per the [design doc](https://github.com/vmware-tanzu/tce/blob/main/docs/designs/standalone-cluster.md#minimizing-the-bill-of-materials-bom), implement a reducing BOM such that the software installed into management clusters is as minimal as possible.

Note this issue is likely dependent on completion of https://github.com/vmware-tanzu/tce/issues/387.

All work done that modifies, adds to, or removes details from the design doc **should include updates to the [design doc](https://github.com/vmware-tanzu/tce/blob/main/docs/designs/standalone-cluster.md#standalone-workload-cluster)**.

**Comment by jpmcb** [comment]
Closing - there is a new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model. Please checkout that proposal and try it out!

Since the current standalone-cluster plugin is being deprecated in a future release, we will not be accepting new features for it.
