### ISSUE TITLE
tanzu/capv too aggressive: if you shutdown a node it deletes it and re-create it from scratch even if the node is good

### ISSUE THREAD

**Issue by gbonazzoli** [vmware-tanzu/community-edition#4139]
In order to simulate faults on the cluster, I shutdown a node (powerOff from vCenter) and in a matter of few minutes the cluster responds to me recreating the same VM with the same name but with a totally new node install.

This is very cloud native !

But if you have a peculiar configuration on the node (in my case some internal certificates) you miss them.
So it seems very necessary to have a mechanism to "append" some custom commands at the node instantiation.

Any other ideas to mitigate the problem ?

**Comment by vrabbi** [comment]
you can add custom commands and files by writing ytt overlays so that new nodes have certificates or anything else needed when being provisioned. you can take a look at my repo https://github.com/TeraSky-OSS/tce-customizations/tree/main/tce-customizations/custom-ytt-overlays/cluster-config-changes
that folder contains examples of such overlays. these would be added to your folder structure on disk where tanzu CLI is installed as per the docs there before creating a cluster and would make it so specific commands or files get added to nodes when being provisioned both at initial deployment as well as any time after that (recreation, upgrade etc.)

**Comment by gbonazzoli** [comment]
@vrabbi  

YYEESSS ! It's the final solution !!!

Many thanks.

**Comment by joshrosso** [comment]
@gbonazzoli looks like we've got a better? way for you to modify these nodes now per @vrabbi's suggestion, are we good to close this out?

Thanks!

**Comment by gbonazzoli** [comment]
Yes, we can close it.

**Comment by gbonazzoli** [comment]
Make "comment" text area happy.
