### ISSUE TITLE
[Unmanaged Cluster] - Enable installing packages (formerly "profiles") at creation from core repo

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/community-edition#4165]
## Feature Request
Currently unless the package is in the tanzu-package-repo-global namespace, it cant be installed at creation time. this makes sense to be the default, but there should be a way to also specify a namespace. this is important for app-toolkit and TAP auto installs as secretgen is in the core repo meaning its in tkg-system and not tanzu-package-repo-global but it isnt installed by default.
this also lines with the issue i opened regarding adding the ability to add a repo to a specific namespace via the additionalRepos feature in which case this becomes even more important.

## Describe alternatives you've considered
to install packages after cluster creation and not via the new feature for auto installation

## Additional context
this effects currently any package that relies on secretgen when running on unmanaged clusters in 0.12.rc2 (Tanzu RabbitMQ, TAP, App Toolkit etc.)

**Comment by seemiller** [comment]
Engineering discussed the idea of allowing namespace specification when pre-installing packages.

**Comment by cmoulliard** [comment]
> Engineering discussed the idea of allowing namespace specification when pre-installing packages.

The problem is that most of the users are not at all aware about the fact that some packages belongs to `repository1`  or `repository2` etc when they create a cluster but simply that they would like to install `packageA`, `packageB`, etc. 

That should be TCE which should resolves that internally without the need to pass `--install-package packageA:repository2`

**Comment by jpmcb** [comment]
> The problem is that most of the users are not at all aware about the fact that some packages belongs to repository1 or repository2

Correct. That is being tracked in: https://github.com/vmware-tanzu/community-edition/issues/4109

But unfortunately, it is possible that there is the same named package in different repositories, only differentiated by their package repository and which namespace they were installed into.

Because package names can be overloaded, we need to enable selecting by namespace.
