### ISSUE TITLE
Investigate ideas to optimize local bootstrapping of standalone clusters

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#427]
## Feature Request

Consider the work done by detiber as a PoC that demonstrates the concept of n embeddable Kubernetes-style API server that supports CRDs [[github project](https://github.com/thetirefire/badidea)] - [[video](https://www.youtube.com/watch?v=n1L5a09wWas)]. I don't think there's any working thing anymore (since that's like 6 months old). In any case, I think it's worth exploring if this is an avenue that can be embedded in the standalone-cluster to provide a mechanism to have management-cluster-less management.

**Comment by jpmcb** [comment]
Closing - there is a new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model with a much liter weight methodology. Please look at the proposal, try it out, and give your feedback there!

Since the current standalone-cluster plugin is being deprecated in a future release, we will not be accepting new features.
