### ISSUE TITLE
Ingress Configuration Options

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu/community-edition#4617]
## Feedback

As a platform engineer (consumer of packages) I want to have a consistent set of options for configuring the ingress components within packages.  Not all packages have ingress, however this suggested consistent approach would apply to that set.  The main point of my feedback is as it pertains to TLS certification information provided via config values to secure the ingress.

Option 1 - Pass namespace and name of secret that contain TLS information ** This is what TAP packages accelerator and tap_gui support today
Option 2 - Pass TLS cert, CA, and private key in values file ** This is what prometheus/harbor/grafana support today
Option 3 - Pass name of cert-manager cluster issuer ** knative-serving takes this today (although knative-serving is a special case and not like the other packages I mentioned).

## Suggested Changes

Ideally, I would want all three options available to me for any package that generates an ingress

Option 3 - Is my favorite, as the package would generate the certificate for the ingress, which in turn generates the secret with the TLS information

Option 2 - This is helpful for demo situations, but really not ideal as rotating certificates involves updating the package

Option 3 - This gives a lot of flexibility, but does have the pre-work that needs to be done prior to deploying the package and if the package is removed, the secret would remain.

So I'd like to have all three options available consistently across the packages.

**Comment by jorgemoralespou** [comment]
Hi,
Ideally the packages (carvel packaging) should support 2 features to properly benefit the users:
- [Package dependency](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/361) so that your package can declare a dependency on cert-manager and properly have cert-manager do the certificate management.
- [Fetch resources from cluster for package deployment](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/410) so that your packages can find if there's a cluster issuer and use it or similar.

With these 2 features, better and more intelligent packages could be crafted. As an alternative, we can implement above 3 options (in the order you describe) but option 1 and 2 creates a lot of intertwingled loosely enforced dependencies that makes our packaging solution not optimal.

To me, what you raise here, is a good topic for greater discussion on what should Carvel packaging need to better support more coherent configurability.
