### ISSUE TITLE
[Docs] Adjust the issue template form when open issues directly via docs

### ISSUE THREAD

**Issue by rguske** [vmware-tanzu/community-edition#4672]
## Description

When selecting **REPORT ISSUE** (see screenshot below) on TCE docs, users will automatically be forwarded to a templated issue-form on Github. The prefabricated issue-title can be confusing though. 

Example: `[Docs] [](/docs/v0.12/package-readme-cert-manager-1.8.0/)` 

Basically, the idea is good to have something in the title which indicates the location where you are on docs when choosing to open an issue on Github. However, this will lead to way too long issue-titles when users understand that it's intended to put the actual title into the brackets `[]`. Rather than appending docs-url to the title, we should automatically put it into the e.g. `Location` section within the issue.

## Location

From my description above, we probably should put e.g. `/docs/v0.12/package-readme-cert-manager-1.8.0/` in here.

## Additional Context

Screenshot:

![image](https://user-images.githubusercontent.com/31652019/171390985-4024d5db-6b61-4dca-98de-b00daee99430.png)

**Comment by stmcginnis** [comment]
Thanks for pointing this out. I've found where this is being done and have an update.

Unfortunately we don't have a way to populate a section of the description from a command line query. But I think it's ok if the title gets a little long, It can always be edited/shortened if needed.

I also noticed another issue because of this. The "Edit" link we had in there does not work since we disabled the ability to create a PR directly on the `main` branch. So clicking on that link would lead to a 404 page. I think the issue link is sufficient, so I am just going to remove the Edit option.
