### ISSUE TITLE
v0.12.1 release not shown as the top of the downloads page

### ISSUE THREAD

**Issue by marckhouzam** [vmware-tanzu/community-edition#4690]
## Description

When looking to download the latest TCE release at https://tanzucommunityedition.io/download/, the release at the top of the page is the v0.12.0 release, while the v0.12.1 release follows it.  I believe this is incorrect, especially from the perspective of a user looking for the more recent release.

The below screenshot shows the wrong order:
![WrongOrder](https://user-images.githubusercontent.com/414402/171535179-abf91faa-ecd7-4794-9593-231463a5c50e.PNG)

## Location

https://tanzucommunityedition.io/download/

## Additional Context

I believe the problem is simply that the date of the v0.12.1 release was not updated and, by being the same as the date of the v0.12.0 release, causes the display order to be incorrect.

I will be posting a PR.

**Comment by Kamlesh356** [comment]
Workload cluster creation failing continuously with below error.

Validating configuration...
Warning: Pinniped configuration not found. Skipping pinniped configuration in workload cluster. Please refer to the documentation to check if you can configure pinniped on workload cluster manually
Creating workload cluster 'aspen-workload-cluster'...
Waiting for cluster to be initialized...
cluster control plane is still being initialized: Bootstrapping @ Machine/aspen-workload-cluster-control-plane-qg8xm
cluster control plane is still being initialized: BootstrapFailed @ Machine/aspen-workload-cluster-control-plane-qg8xm
Error: unable to wait for cluster and get the cluster kubeconfig: error waiting for cluster to be provisioned (this may take a few minutes): timed out waiting for cluster creation to complete: cluster control plane is still being initialized: BootstrapFailed @ Machine/aspen-workload-cluster-control-plane-qg8xm
Usage:
  tanzu cluster create CLUSTER_NAME [flags]

Flags:
  -d, --dry-run       Does not create cluster, but show the deployment YAML instead
  -f, --file string   Configuration file from which to create a cluster
  -h, --help          help for create
      --tkr string    TanzuKubernetesRelease(TKr) to be used for creating the workload cluster. If TKr name prefix is provided, the latest compatible TKr matching the TKr name prefix would be used

Global Flags:
      --log-file string   Log file path
  -v, --verbose int32     Number for the log level verbosity(0-9)

Error: exit status 1

✖  exit status 1 

======

Also many a times getting the below warning messages while running kubectl basic comands(getting cluster list , getting the nodes etc)

I0718 09:45:34.355269 3127426 request.go:665] Waited for 1.14311046s due to client-side throttling, not priority and fairness, request: GET:https://172.19.0.11:6443/apis/acme.cert-manager.io/v1alpha3?timeout=32s
