### ISSUE TITLE
install.sh fails if `sudo` is not in the `PATH`

### ISSUE THREAD

**Issue by alinahid477** [vmware-tanzu/community-edition#4957]
In the install.sh file at line:84 (`sudo install "${MY_DIR}/tanzu" "${TANZU_BIN_PATH}" || handle_sudo_failure`). This line does not take ALLOW_INSTALL_AS_ROOT=true into consideration (upon inspecting I did not find implementation for handle_sudo_failure). As a result when logged in as root user the install.sh script fails to install tanzu cli.

TCE version: 0.12.1

Error:
=========
When logged in as root and executing ./install.sh under dir ~/tanzu/tce-linux-amd64-v0.12.1/ despite setting `ALLOW_INSTALL_AS_ROOT=true` the script yields error and fails to install tanzu on host machine. 

Error Message:
==============
```
Installing tanzu cli to /usr/local/bin/tanzu
./install.sh: line 84: sudo: command not found
./install.sh: line 84: handle_sudo_failure: command not found

./install.sh: line 111: tanzu: command not found
./install.sh: line 112: tanzu: command not found
./install.sh: line 114: tanzu: command not found
./install.sh: line 116: tanzu: command not found
./install.sh: line 118: tanzu: command not found
```

expected behavior:
==============
When export ALLOW_INSTALL_AS_ROOT=true the script to successfully install tanzu cli is expected. The script should not throw error due to not being able to use sudo command. A condition or an appropriate usage implementation of handle_suro_failure should tackle the issue.

Thanks

**Comment by stmcginnis** [comment]
Hi @alinahid477 - the missing `handle_sudo_failure` was fixed in https://github.com/vmware-tanzu/community-edition/pull/4550. That is waiting for a new release, but you could apply that change to your local `install.sh` script.

It appears `ALLOW_INSTALL_AS_ROOT` is working fine, otherwise the script would fail immediately and notify you it was not allowed:

https://github.com/vmware-tanzu/community-edition/blob/main/hack/release/install.sh#L40-L42

So the other than the `handle_sudo_failure` part missing, it looks like this is failing because for some reason your system is missing the `sudo` command. This should be fine to be called by root (root can run as root), but the command itself is just not in the path: `sudo: command not found`.

So either `sudo` needs to available in your `PATH` or you will need to create a `~/bin` directory in your home directory and add that to your PATH:

```
mkdir ~/bin
export PATH=$PATH:~/bin
install.sh
```

**Comment by alinahid477** [comment]
Hi @stmcginnis 
Thanks for the update. 

Great to hear that `handle_sudo_failure` fix is going to be released soon.

Regarding `sudo` fail: not sure I follow. 
If I am logged in as root in Linux (mint / debian disti) there's no sudo in the path (and shouldn't be as root use does not require sudo). Hence, a command in the `install.sh` file that requires sudo does not make sense when `ALLOW_INSTALL_AS_ROOT=true` , assuming the purpose of that var is to allow root user to run the script.

I would imagine the below logic would be applied instead (and that's what I have changed in my local for now. However, hoping that the distribution will be bug free):

previous (bug) code:
==================
`sudo install "${MY_DIR}/tanzu" "${TANZU_BIN_PATH}" || handle_sudo_failure`


new code (bug fix):
==================
```
if  $ALLOW_INSTALL_AS_ROOT 
then
   install "${MY_DIR}/tanzu" "${TANZU_BIN_PATH}" || handle_sudo_failure
else
  sudo install "${MY_DIR}/tanzu" "${TANZU_BIN_PATH}" || handle_sudo_failure
fi
```

**Comment by stmcginnis** [comment]
That's fair. Most distros still have `sudo` in the path, so root calling sudo just ends up being an noop.

This sounds like a reasonable approach to handle this case where `sudo` is not in the path. The conditional branching shouldn't be on `ALLOW_INSTALL_AS_ROOT` though, since that just allows the script to run. It doesn't necessarily guarantee the user actually is root. So maybe something like:

```
TANZU_BIN_PATH="/usr/local/bin"
if [[ ":${PATH}:" == *":$HOME/bin:"* && -d "${HOME}/bin" ]]; then
  TANZU_BIN_PATH="${HOME}/bin"
  echo Installing tanzu cli to "${TANZU_BIN_PATH}/tanzu"
  install "${MY_DIR}/tanzu" "${TANZU_BIN_PATH}"
elif [[ "$EUID" -eq 0 ]]; then
  echo Installing tanzu cli to "${TANZU_BIN_PATH}/tanzu"
  install "${MY_DIR}/tanzu" "${TANZU_BIN_PATH}"
else
  echo Installing tanzu cli to "${TANZU_BIN_PATH}/tanzu"
  sudo install "${MY_DIR}/tanzu" "${TANZU_BIN_PATH}" || handle_sudo_failure
fi
```
 
Do you want to submit a PR to add this? If not, I can submit a patch. Just let me know. Thanks!

**Comment by alinahid477** [comment]
@stmcginnis your code is elegant and yes please submit a patch. 
Thanks a lot for looking into this.
