### ISSUE TITLE
Figure out what to do with Grafana (new licensing)

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#536]
## Feedback

Grafana has switched their licensing to AGPL. Which raises a question for whether we can repackage and distribute Grafana in TCE.

**Comment by joshrosso** [comment]
Handed this issue over to @seemiller to work with various teams and determine what we're going to do via the license change.

**Comment by seemiller** [comment]
Due to the concerns with bundling/distributing a package containing AGPL-3.0 licensed software, we will not be providing a package with any Grafana 8.x versions.

In light of this, options are as follows:
* Continue to update the current Grafana package to utilize the latest versions of the 7.5.x release branch.
* Retire the Grafana package
* Adopt a suitable alternative to Grafana
* Allow the community to create and publish a Grafana 8.x package

Given these options, we will continue to update the existing Grafana package with the latest 7.5.x releases.

**Comment by kartiklunkad26** [comment]
@seemiller have we checked with our user community if we have a large community of users of Grafana? Wondering if it's something we can fully remove in case it isn't heavily used?
