### ISSUE TITLE
Standalone Azure UI asks for separate control plane and worker node subnet info

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#692]
## Bug Report

The deployment UI for a standalone cluster on Azure asks for separate control plane and worker node subnet information under the "Azure VNET Settings" section of the deployment wizard.

## Expected Behavior

There should only be one subnet required when deploying a standalone cluster. UI should only ask for one.

## Steps to Reproduce the Bug

Run `tanzu standalone-cluster create az --ui` and follow the wizard steps to the VNET for Azure group.

## Environment Details

* Build version (`tanzu version`):  v0.5.0-rc.3 local build
* Operating System (client): darwin

**Comment by jpmcb** [comment]
Closing - there is a new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model with a much liter weight methodology. Please look at the proposal, try it out, and give your feedback there!

Since the current standalone-cluster plugin is being deprecated in a future release, we will not be accepting new features.
