### ISSUE TITLE
Need `tanzu standalone-cluster list` command

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#703]
## Feedback

With management-clusters and workload clusters, there are `tanzu management-cluster list` and `tanzu cluster list` commands to be able to view these instances.

When deploying standalone cluster though, we don't have any mechanism to view what has been deployed. We need an equivalent (`tanzu standalone-cluster list`) command so a user can see what is out there.

## Suggested Changes

Add `tanzu standalone-cluster list` command to list the names of the standalone clusters we have persisted.

**Comment by jpmcb** [comment]
Closing - there is a new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model with a much liter weight methodology. Please look at the proposal, try it out, and give your feedback there!

Since the current standalone-cluster plugin is being deprecated in a future release, we will not be accepting new features.
