### ISSUE TITLE
Need docs for standalone cluster metadata capture

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#704]
## Feedback

We save off metadata about standalone clusters so we can do `tanzu standalone-cluster delete`. But this assumes these standalone clusters will only ever be managed from the same machine. Probably pretty safe with the docker deployment, but I could see a cloud provider deployment being accessed from multiple locations.

It's also a concern if something were to happen to the originating machine. It's possible to manually clean up a standalone cluster outside of the CLI, but it's certainly not user friendly.

## Suggested Changes

We should add documentation to the standalone cluster deployment instructions explaining how to back up or move this data so `tanzu standalone-cluster delete` can be run from another machine.

**Comment by jpmcb** [comment]
Closing - there is a new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model with a much liter weight methodology. Please look at the proposal, try it out, and give your feedback there!

Since the current standalone-cluster plugin is being deprecated in a future release, we will not be accepting new features.
