### ISSUE TITLE
Create a PR in core featuring standalone-cluster creation and deletion

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#713]
Now that tkg-cli is inside core, let's bring a PR in for our initstandalone functionality.

**Comment by jpmcb** [comment]
Closing - there is a new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model with a much liter weight methodology. Please look at the proposal, try it out, and give your feedback there!

Since the current standalone-cluster plugin is being deprecated in a future release, we will not be accepting new features.
