### ISSUE TITLE
Docker standalone-cluster flags

### ISSUE THREAD

**Issue by embano1** [vmware-tanzu/community-edition#843]
## Feedback

Some flags (at least their doc strings) in `tanzu standalone-cluster create` seem a bit misleading/lack of details.

Example 1: 

`-i, --infrastructure string   Infrastructure to deploy the standalone cluster on. Only needed when using -i docker.` < but apparently the other infrastructure providers don't need it - so why have this flag at all?

Example 2:

`-f, --file string             Configuration file from which to create a standalone cluster`. I could not find documentation about the configuration file format (not in the docs either). Is this a valid `kind` config file?

## Suggested Changes

Example 1:

Instead of `-i docker` make it `-docker` to indicate a docker option and not confuse this flag with other infrastructures, e.g. vsphere. Unless in future releases we want to open `-i` for other infra providers. Then consider rewording the help to provide the supported ENUMs, e.g. `Infrastructure to deploy the standalone cluster on. Valid options: "docker"` and later expand the section with other providers.

Example 2:

Give details on the expected configuration file, e.g. `kind config`, etc.

## Environment Details

* Build version (`tanzu version`):

tanzu version
version: v1.3.0
buildDate: 2021-06-03
sha: b261a8b

  
* Operating System (client): OSX

**Comment by jpmcb** [comment]
Closing - there is a new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model with a much liter weight methodology. Please look at the proposal, try it out, and give your feedback there!

Since the current standalone-cluster plugin is being deprecated in a future release, we will not be accepting new features.
