### ISSUE TITLE
Deleing standalone clusters should not _always_ require the re-creation of a management cluster

### ISSUE THREAD

**Issue by embano1** [vmware-tanzu/community-edition#844]
## Feedback

This puzzled me:

```
tanzu standalone-cluster delete $GUEST_CLUSTER_NAME
Loading bootstrap cluster config for standalone cluster at '/Users/mgasch/.tanzu/tce/configs/tce-01_ClusterConfig'
no bootstrap cluster config found - looking for UI bootstrap config file
Loading UI bootstrap cluster config for standalone cluster at '/Users/mgasch/.tanzu/clusterconfigs/tce-01.yaml'
no bootstrap cluster config found - using default config
timeout duration of at least 15 minutes is required, using default timeout 30m0s
Deleting standalone cluster 'tce-01'. Are you sure? [y/N]: y

Deleting standalone cluster...

loading cluster config file at
cluster config file not provided using default config file at '/Users/mgasch/.tanzu/cluster-config.yaml'
Setting up cleanup cluster...
Fetching configuration for kind node image...
```

## Suggested Changes

Explain why a cleanup cluster is required or get rid of a cleanup cluster if I simply want to delete my standalone (throw-away) cluster.

## Environment Details

* Build version (`tanzu version`):  
* Operating System (client):

**Comment by jpmcb** [comment]
Closing - there is a new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model with a much liter weight methodology. Please look at the proposal, try it out, and give your feedback there!

In the new model, a management cluster does _not_ also come up (but we loose some of the cluster lifecycle abilities)

Since the current standalone-cluster plugin is being deprecated in a future release, we will not be accepting new features.
