### ISSUE TITLE
 tanzu standalone-cluster create does not work on Windows WSL2

### ISSUE THREAD

**Issue by thesteve0** [vmware-tanzu/community-edition#849]
## Bug Report

`tanzu standalone-cluster create -i docker` does not work in WSL2 on Windows. I am using Ubuntu 20.04 on Windows 10 with WSL integrated Docker. 

All the containers spin up but this error starts appearing in the install output
`Failed to invoke API on cluster : Get "https://172.17.0.3:6443/version?timeout=32s": dial tcp 172.17.0.3:6443: i/o timeout, retrying`

Eventually it times out and fails. So it seems that the KIND cluster is up but it can't communicate over the cluster API.

Based on the behavior we see, we think this is due to not doing the node mapping that is required with KIND on WSL2
https://kind.sigs.k8s.io/docs/user/using-wsl2/

## Expected Behavior
Run the command an you get a functional cluster. 

## Steps to Reproduce the Bug

Run the command above in a WSL2 system 

## Environment Details

* Build version (`tanzu version`):  0.5
* Operating System (client): Ubuntu 20.04

**Comment by jpmcb** [comment]
Closing - there is a new [standalone-cluster proposal](https://github.com/vmware-tanzu/community-edition/issues/2266) that uses a different model with a much liter weight methodology. Please look at the proposal, try it out, and give your feedback there!

And good news! With this new overhaul, it works great on WSL2!

Since the current standalone-cluster plugin is being deprecated in a future release, we will not be accepting new features.
